# Site settings
title: dpitt.me
name: dan pittman
description:
baseurl: ''
url: "http://dpitt.me"
collections:
  talks:
    output: true
  weeklies:
    output: true

# Build settings
markdown: kramdown
permalink: pretty
