flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- monad-gen-0.3.0.1
- pandoc-sidenote-0.19.0.0
- hakyll-4.13.0.1
- lrucache-1.2.0.1
resolver: lts-14.6
nix:
  enable: true
  packages: [zlib.dev, zlib.out]
